# Generated by Django 4.2.3 on 2023-07-22 05:10

from django.db import migrations, models

def create_data(apps, schema_editor):
    Entry = apps.get_model('entries', 'Entry')
    Entry(name="John Smith", email= "jsmith@test.com", comments="Let's run fast!", select="Yes", raceOption="5k").save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.RunPython(create_data),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField()),
                ('select', models.CharField(max_length=10)),
                ('raceOption', models.CharField(max_length=10)),
            ],
        ),
    ]
